---
- homebrew:
    update_homebrew: yes
    upgrade_all: no

- homebrew_tap:
    name: "{{ item }}"
  loop:
    - beeftornado/rmtree
    - homebrew/cask-fonts
    - homebrew/cask-drivers

- homebrew:
    name: "{{ item }}"
  loop:
    - antigen
    - bash-completion
    - coreutils
    - fzf
    - fasd
    - hub
    - ripgrep
    - zsh
    - pipenv
    - pyenv
    - direnv

- name: Run homebrew caveats.
  shell: "{{ item }}"
  loop:
    - "$(brew --prefix)/opt/fzf/install"

- homebrew_cask:
    name: "{{ item }}"
  loop:
    - 1password
    # - adobe-creative-cloud
    - appcleaner
    - bettertouchtool
    - caprine
    - dash
    - discord
    - docker
    - font-inconsolata-dz-for-powerline
    - google-chrome
    - iterm2
    - hammerspoon
    - karabiner-elements
    # - logitech-gaming-software
    - spotify
    - visual-studio-code
    - slack

- homebrew_cask:
    name: "{{ item }}"
  loop:
    - nvidia-web-driver
    - clover-configurator
  when: is_hackintosh | bool
